<?php
// Japanese language-texts.
// Version 1.9.6-dev
// This file is only meant as a basis for you to do your own translation!
// Read our wiki on how to translate: http://code.google.com/p/phpliteadmin/wiki/Localization
// --------------------------------------------- 
// phpliteAdmin 日本語ファイル  
// Version 1.9.6-ja00 ･･75%
// https://github.com/bbfriend/phpliteAdmin_japanese
// --------------------------------------------- 
$lang = array(
	"direction" => "LTR",
	"date_format" => 'Y/m/d H:i:s',  // see http://php.net/manual/en/function.date.php for what the letters stand for
	"ver" => "バージョン",
	"for" => "for",
	"to" => "to",
	"go" => "Go",
	"yes" => "はい",
	"no" => "いいえ",
	"sql" => "SQL",
	"csv" => "CSV",
	"csv_tbl" => "CSVファイル関連テーブル",
	"srch" => "検索",
	"srch_again" => "再度検索する",
	"login" => "ログイン",
	"logout" => "ログアウト",
	"view" => "ビュー",
	"confirm" => "確認",
	"cancel" => "キャンセル",
	"save_as" => "保存",
	"options" => "オプション",
	"no_opt" => "オプションなし",
	"help" => "ヘルプ",
	"installed" => "installed",
	"not_installed" => "not installed",
	"done" => "done",
	"insert" => "挿入",
	"export" => "エクスポート",
	"import" => "インポート",
	"rename" => "変更",
	"empty" => "空にする",
	"drop" => "削除",
	"tbl" => "テーブル",
	"chart" => "Chart",
	"err" => "エラー",
	"act" => "操作",
	"rec" => "レコード",
	"col" => "カラム",
	"cols" => "カラム",
	"rows" => "行)",
	"edit" => "編集",
	"del" => "削除",
	"add" => "追加",
	"backup" => "データベースファイルを保存する",
	"before" => "前",
	"after" => "後",
	"passwd" => "パスワード",
	"passwd_incorrect" => "パスワードが間違っています。",
	"chk_ext" => "サポートされているSQLite PHP拡張機能をチェックする",
	"autoincrement" => "Autoincrement",
	"not_null" => "Not NULL",
	"attention" => "注意",
	"none" => "None",
	"as_defined" => "定義通り",
	"expression" => "Expression",
	
	"sqlite_ext" => "SQLite拡張機能",
	"sqlite_ext_support" => "あなたのPHPでは、サポートされているSQLiteライブラリ拡張が利用できないようです。 少なくとも1つをインストールするまで %s を使用することはできません。",
	"sqlite_v" => "SQLiteのバージョン",
	"sqlite_v_error" => "It appears that your database is of SQLite version %s but your installation of PHP does not contain the necessary extensions to handle this version. To fix the problem, either delete the database and allow %s to create it automatically or recreate it manually as SQLite version %s.",
	"report_issue" => "The problem cannot be diagnosed properly. Please file an issue report at",
	"sqlite_limit" => "Due to the limitations of SQLite, only the field name and data type can be modified.",
	
	"php_v" => "PHPバージョン",
	"new_version" => "新しいバージョンがあります！",
	
	"db_dump" => "データベースダンプ",
	"db_f" => "データベースファイル",
	"db_ch" => "データベースの変更",
	"db_event" => "データベースイベント",
	"db_name" => "データベース名",
	"db_rename" => "データベースの名前を変更する",
	"db_renamed" => "データベース '%s' の名前→",
	"db_del" => "データベースの削除",
	"db_path" => "データベースへのパス",
	"db_size" => "データベースのサイズ",
	"db_mod" => "データベースの最終更新日",
	"db_create" => "新しいデータベースを作成する",
	"db_vac" => "データベース, '%s'は、アップグレードされました。.",
	"db_not_writeable" => "データベース '%s', 存在しない。もしくは '%s' が書込み可能でありません。フォルダを書き込み可能にするまで、アプリケーションが使用することはできません",
	"db_setup" => "データベース: %s の設定に問題がありました。 An attempt will be made to find out what's going on so you can fix the problem more easily",
	"db_exists" => "データベース、別のファイル、または '%s' という名前のディレクトリが既に存在します。",
	
	"exported" => "Exported",
	"struct" => "構造",
	"struct_for" => "構造",
	"on_tbl" => "on table",
	"data_dump" => "Data dump for",
	"backup_hint" => "ヒント：データベースをバックアップするには、最も簡単な方法は %s を保存することです。",
	"backup_hint_linktext" => "download the database-file",
	"total_rows" => "a total of %s rows",
	"total" => "Total",
	"not_dir" => "データベースを検索するために指定したディレクトリが存在しないか、ディレクトリではありません。",
	"bad_php_directive" => "It appears that the PHP directive, 'register_globals' is enabled. This is bad. You need to disable it before continuing.",
	"page_gen" => "%s でページが生成されました。",
	"powered" => "Powered by",
	"free_software" => "これはフリーソフトウェアです。",
	"please_donate" => "開発のために寄付してください。",
	"remember" => "Remember me",
	"no_db" => "%s へようこそ。管理するデータベースのディレクトリをスキャンしたようですが、%s は有効なSQLiteデータベースを見つけることができませんでした。Welcome to %s. ",
	"no_db2" => "The directory you specified does not contain any existing databases to manage, and the directory is not writable. This means you can't create any new databases using %s. Either make the directory writable or manually upload databases to the directory.",
	
	"create" => "作成",
	"created" => "作成されました",
	"create_tbl" => "新しいテーブルを作成する",
	"create_tbl_db" => "データベースに新しいテーブルを作成する",
	"create_trigger" => "テーブルに新しいトリガを作成する",
	"create_index" => "テーブルに新しいインデックスを作成する",
	"create_index1" => "Create Index",
	"create_view" => "データベース上に新しいビューを作成する",
	
	"trigger" => "トリガ",
	"triggers" => "トリガ",
	"trigger_name" => "トリガ名",
	"trigger_act" => "トリガ 操作",
	"trigger_step" => "トリガステップ（セミコロンで区切）",
	"when_exp" => "WHEN式（WHEN 'を除いた同じ条件を与える）",
	"index" => "インデックス",
	"indexes" => "インデックス",
	"index_name" => "インデックス名",
	"name" => "Name",
	"unique" => "Unique",
	"seq_no" => "Seq. No.",
	"emptied" => "空になりました",
	"dropped" => "has been dropped",
	"renamed" => "has been renamed to",
	"altered" => "正常に変更されました",
	"inserted" => "inserted",
	"deleted" => "deleted",
	"affected" => "affected",
	"blank_index" => "インデックス名は空白であってはいけません。",
	"one_index" => "少なくとも1つのインデックス付きの列を指定する必要があります。",
	"docu" => "ドキュメント",
	"license" => "ライセンス",
	"proj_site" => "プロジェクトページ",
	"bug_report" => "これは報告する必要のあるバグかもしれません",
	"return" => "Return",
	"browse" => "Browse",
	"fld" => "フィールド",
	"fld_num" => "フィールド数",
	"fields" => "Fields",
	"type" => "Type",
	"operator" => "Operator",
	"val" => "Value",
	"update" => "Update",
	"comments" => "Comments",
	
	"specify_fields" => "テーブルフィールドの数を指定する必要があります",
	"specify_tbl" => "テーブル名を指定する必要があります。",
	"specify_col" => "列を指定する必要があります。",
	
	"tbl_exists" => "同じ名前のテーブルが既に存在します。",
	"show" => "Show",
	"show_rows" => " %s 行を表示しています。",
	"showing" => "表示中",
	"showing_rows" => "行を表示する",
	"query_time" => "(Query took %s sec)",
	"syntax_err" => "クエリの構文に問題があります（クエリは実行されませんでした）",
	"run_sql" => "データーベース '%s' にSQLクエリ/クエリを実行します。",
	"recent_queries" => "Recent Queries",
	"full_texts" => "フルテキストを表示",
	"no_full_texts" => "長いテキストを短くする",
	
	"ques_empty" => "本当にテーブル '%s' を空にしますか？",
	"ques_drop" => "本当にテーブル '%s' を削除しますか？",
	"ques_drop_view" => "ビュー '%s' を削除してもよろしいですか？",
	"ques_del_rows" => "行％sをテーブル '％s' から削除してもよろしいですか？",
	"ques_del_db" => "本当にデータベース '%s' を削除しますか？",
	"ques_column_delete" => "カラム %s をテーブル '%s' から削除してもよろしいですか？",
	"ques_del_index" => "本当にインデックス '%s' を削除しますか？",
	"ques_del_trigger" => "本当にトリガー '%s' を削除しますか？",
	"ques_primarykey_add" => "カラム%s にテーブル '%s' のプライマリキーを追加してもよろしいですか？",
	
	"export_struct" => "構造体でエクスポート",
	"export_data" => "データでエクスポート",
	"add_drop" => "DROP TABLEを追加",
	"add_transact" => "TRANSACTIONを追加",
	"fld_terminated" => "ヘッダ名の区切り文字",
	"fld_enclosed" => "Fields enclosed by",
	"fld_escaped" => "Fields escaped by",
	"fld_names" => "最初の行のヘッダー名",
	"rep_null" => "Replace NULL by",
	"rem_crlf" => "ヘッダーからCRLF文字を削除する",
	"put_fld" => "最初の行にヘッダー名を配置する",
	"null_represent" => "NULL represented by",
	"import_suc" => "インポートに成功しました",
	"import_into" => "Import into",
	"import_f" => "インポートするファイル",
	"rename_tbl" => "Rename table '%s' to",
	
	"rows_records" => "レコード番号から始まる行 # ",
	"rows_aff" => "影響を受ける行. ",
	
	"as_a" => "as a",
	"readonly_tbl" => "'%s' is a view, which means it is a SELECT statement treated as a read-only table. You may not edit or insert records.",
	"chk_all" => "すべてチェック",
	"unchk_all" => "すべてチェックを外す",
	"with_sel" => "選択済み",
	
	"no_tbl" => "データベースにテーブルがありません。",
	"no_chart" => "これを読むことができれば、グラフが生成できないことを意味します。表示しようとしているデータがグラフに適していない可能性があります。",
	"no_rows" => "選択した範囲のテーブルに行がありません。",
	"no_sel" => "あなたは何も選択していませんでした。",
	
	"chart_type" => "グラフタイプ",
	"chart_bar" => "棒グラフ",
	"chart_pie" => "円グラフ",
	"chart_line" => "折れ線グラフ",
	"lbl" => "Labels",
	"empty_tbl" => "このテーブルは空です。",
	"click" => "ここをクリック",
	"insert_rows" => "行を挿入する",
	"restart_insert" => "再び挿入を開始する ",
	"ignore" => "Ignore",
	"func" => "Function",
	"new_insert" => "新しい行として貼り付け",
	"save_ch" => "変更を保存する",
	"def_val" => "デフォルト値",
	"prim_key" => "主キー",
	"tbl_end" => "テーブルの最後にフィールドを追加",
	"query_used_table" => "このテーブルを生成するために使用される式",
	"query_used_view" => "このビューを生成するための式",
	"create_index2" => "インデックスを作成する",
	"create_trigger2" => "新しいトリガーを作成する",
	"new_fld" => "テーブル '%s' に新しいフィールドを追加します",
	"add_flds" => "フィールドを追加",
	"edit_col" => "カラム '%s' を編集します。 ",
	"vac" => "Vacuum",
	"vac_desc" => "大規模なデータベースは、サーバー上のサイズを小さくするために 不要な領域を整理し最適化（Vacuum）する必要があります。データベース '%s' を Vacuum するには下のボタンをクリックしてください。",
	"event" => "Event",
	"each_row" => "For Each Row",
	"define_index" => "インデックスプロパティを指定する",
	"dup_val" => "Duplicate values",
	"allow" => "Allowed",
	"not_allow" => "許可させていません",
	"asc" => "昇順",
	"desc" => "降順",
	"warn0" => "警告されました",
	"warn_passwd" => "デフォルトのパスワードを使用しています。これは危険な可能性があります。あなたは %s の上で簡単に変更できます。",
	"warn_dumbass" => "You didn't change the value dumbass ;-)",
	"counting_skipped" => "データベースが比較的大きく、いくつかのテーブルのレコード数のカウントはスキップされました。一部の表には主キーが定義されていないため、レコードのカウントに時間がかかることがあります。プライマリキーを追加するか,or %s force counting %s.",
	"sel_state" => "式の選択",
	"delimit" => "別々の式",
	"back_top" => "Back to Top",
	"choose_f" => "ファイルを選択",
	"instead" => "代わりに",
	"define_in_col" => "カラム（列）のインデックスを選択する",
	
	"delete_only_managed" => "このツールで管理されているデータベースのみを削除できます！",
	"rename_only_managed" => "このツールで管理されているデータベースの名前を変更できるだけです！",
	"db_moved_outside" => "You either tried to move the database into a directory where it cannot be managed anylonger, or the check if you did this failed because of missing rights.",
	"extension_not_allowed" => "指定されたファイル拡張子は、許可されたファイル拡張子のリストにありません。次のファイル拡張子のいずれかを使用してください",
	"add_allowed_extension" => "You can add extensions to this list by adding your extension to \$allowed_extensions in the configuration.",
	"directory_not_writable" => "The database-file itself is writable, but to write into it, the containing directory needs to be writable as well. This is because SQLite puts temporary files in there for locking.",
	"tbl_inexistent" => "テーブル %s は存在しません",

	// errors that can happen when ALTER TABLE fails. You don't necessarily have to translate these.
	"alter_failed" => "テーブル %s への変更に失敗しました",
	"alter_tbl_name_not_replacable" => "テーブル名を一時テーブルに置き換えることができませんでした",
	"alter_no_def" => "ALTER定義なし",
	"alter_parse_failed" =>"ALTER定義の解析に失敗しました",
	"alter_action_not_recognized" => "ALTERアクションを認識できませんでした",
	"alter_no_add_col" => "ALTER式で検出されるカラムが見つかりません",
	"alter_pattern_mismatch"=>"CREATE TABLE式がパターンに合いません",
	"alter_col_not_recognized" => "新しいカラム名または古いカラム名を認識できませんでした",
	"alter_unknown_operation" => "不明なALTER操作です！",
	
	/* Help documentation */
	"help_doc" => "ヘルプドキュメント",
	"help1" => "SQLite対応拡張機能",
	"help1_x" => "%s は、PHPライブラリ拡張(extension)を使用してSQLiteデータベースとの対話を可能にします。 現在、%s はPDO、SQLite3、SQLiteDatabaseをサポートしています。 PDOとSQLite3の両方がSQLiteバージョン3を処理し、SQLiteDatabaseがバージョン2を処理します。PHPインストールに複数のSQLiteライブラリ拡張が含まれる場合、PDOとSQLite3が優先されます。 ただし、既存のデータベースがSQLiteバージョン2の場合、%s はこれらのデータベースに対してのみSQLiteDatabaseを使用するよう強制されます。 すべてのデータベースが同じバージョンである必要はありません。 ただし、データベースの作成時には、最も高度な拡張機能が使用されます。",
	"help2" => "データベースの作成",
	"help2_x" => "新しいデータベースを作成するときは、自分で入力しないと、入力した名前に適切なファイル拡張子（.db、.db3、.sqliteなど）が追加されます。 \$directory変数として指定したディレクトリに作成されます。",
	"help3" => "テーブルとビュー",
	"help3_x" => "On the main database page, there is a list of tables and views. Since views are read-only, certain operations will be disabled. These disabled operations will be apparent by their omission in the location where they should appear on the row for a view. If you want to change the data for a view, you need to drop that view and create a new view with the appropriate SELECT statement that queries other existing tables. For more information, see <a href='http://en.wikipedia.org/wiki/View_(database)' target='_blank'>http://en.wikipedia.org/wiki/View_(database)</a>",
	"help4" => "新しいビューのSELECT文を作成",
	"help4_x" => "新しいビューを作成するSQLのSELECT文。ビューとは、読み取り専用の仮想的なテーブルで、1つまたは複数のテーブルの中から一部分だけを取り出しあたかも別のテーブルのように扱うことができるようにしたものです。データの更新や追加はできません。列または行を編集するこのビューは、選択したデータを便利に取得するためにのみ使用されます。",
	"help5" => "構造をSQLファイルにエクスポート",
	"help5_x" => "During the process for exporting to an SQL file, you may choose to include the queries that create the table and columns.",
	"help6" => "データをSQLファイルにエクスポート",
	"help6_x" => "During the process for exporting to an SQL file, you may choose to include the queries that populate the table(s) with the current records of the table(s).",
	"help7" => "エクスポートされたSQLファイルにDROP TABLEを追加",
	"help7_x" => "During the process for exporting to an SQL file, you may choose to include queries to DROP the existing tables before adding them so that problems do not occur when trying to create tables that already exist.",
	"help8" => "エクスポートされたSQLファイルにTRANSACTIONを追加",
	"help8_x" => "During the process for exporting to an SQL file, you may choose to wrap the queries around a TRANSACTION so that if an error occurs at any time during the importation process using the exported file, the database can be reverted to its previous state, preventing partially updated data from populating the database.",
	"help9" => "エクスポートされたSQLファイルにコメントを追加する",
	"help9_x" => "During the process for exporting to an SQL file, you may choose to include comments that explain each step of the process so that a human can better understand what is happening."

);
